### ISSUE TITLE
Cast a float value inside a string to integer

### ISSUE THREAD

**Issue by danielveloso09** [mjacobus/koine-attributes#19]
First of all, this is just a could have, not really important thingy.

if you have:
```
class SomeClass
  include Koine::Attributes

  attributes do
    attribute :id, :integer
  end
end
```

and when for some reason you try SomeClass.new(id: '1.0') it will give you an error, the same thing for type :float it works.

Possible solution would be in 'lib/koine/attributes/adapter/integer.rb', to cast to Float first and then to Integer, but dont really like this solution.

Cumps @mjacobus

**Comment by mjacobus** [comment]
Hey there!

That is by design. If given id isa float, that means the data passed in is invalid. So an error should be raised.

You can always use a custom adapter, but I suppose the best solution would be to make sure you are not passing stringified floats.

Also fee free to change the adapter by adding the option to take floats (or filter them before actually doing the casting to integer), but if you do, please make sure it keeps the current behaviour as default.
